name: Metrics

on:
  push:
  schedule:
    - cron: "0 0 * * *"  # atualiza diariamente Ã  meia-noite UTC (opcional)

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Run lowlighter/metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg
          template: classic
          base: header, repositories
          plugins: anilist
          plugin_anilist: yes
          plugin_anilist_user: "etsvb"
          plugin_anilist_medias: "anime,manga"
          plugin_anilist_sections: "favorites"
          plugin_anilist_limit: 10
          plugin_anilist_shuffle: yes
